name: Style Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Check Code format
      run: |
        ./scripts/check_code_style.sh .
      shell: bash
